version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP port for client connections
      - "15672:15672" # Management UI port
  mysql:
    image: mysql:8
    container_name: casha
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Demo1234
      MYSQL_DATABASE: casha
    volumes:
      - ./mysql_data:/var/lib/mysql
  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger-casha
    ports:
      # Jaeger UI
      - "16686:16686"
      # OTLP gRPC receiver
      - "4317:4317"
      # OTLP HTTP receiver (if you prefer, but gRPC is generally recommended)
      - "4318:4318"
      # Jaeger native Thrift HTTP receiver (for older Jaeger clients)
      - "14268:14268"
      # Jaeger native Thrift compact receiver (for older Jaeger clients)
      - "6831:6831/udp"
    environment:
      # Enable OTLP receivers
      - COLLECTOR_OTLP_ENABLED=true
      # Configure gRPC for OTLP
      - COLLECTOR_OTLP_GRPC_HOST_PORT=:4317
      # Configure HTTP for OTLP
      - COLLECTOR_OTLP_HTTP_HOST_PORT=:4318
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge

