databaseType = "MySql"
id = "e7903a97-cd76-4550-bd84-d9f63ecc5c4b"
name = "auth-casha"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.auth-casha]
url = "jdbc:mysql://localhost:3306?allowPublicKeyRetrieval=true"
schemas = [ "auth-casha" ]
displayName = "auth-casha"
